ONE_MONTH_SUBSCRIBE_DETAILS:
  currency: !!str rub
  photo_width: !!int 416
  photo_height: !!int 234
  photo_size: !!int 416
  provider_token: !!str 381764678:TEST:32054
  is_flexible: !!bool false
  need_shipping_address: !!bool false
DISCOUNTS:
  global: !!int 10
  inviting: !!int 15
